backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"
locale: "es"

collections:
  - name: "posts"
    label: "Artículos"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha",  name: "date",  widget: "datetime" }
      - { label: "Resumen (opcional)", name: "excerpt", widget: "text", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
